### ISSUE TITLE
SenseEval support

### ISSUE THREAD

**Issue by oxinabox** [JuliaText/CorpusLoaders.jl#9] opened 2018-04-20 07:30 UTC
Rada Mihalcea provides then SenseEval corpora 2 and 3,
in SemCor format
http://web.eecs.umich.edu/~mihalcea/downloads.html#sensevalsemcor

Thus because we have a SemCor parser already we basically already support them.
It is more a matter of writing the data deps registration,
than any real parsing.

This would be a good and easy PR to make

**Comment by ksteimel** [comment] 2018-04-26 03:32
I can help out with this after next week. However, should I wait until your 'fresh' branch is merged?

**Comment by oxinabox** [comment] 2018-04-26 06:02
Yes, I'll try and merge it before next week then.
It's vaguely waiting for me to port more stuff from the old version, though I can look up the old version from it's tag.

**Comment by oxinabox** [comment] 2018-06-14 04:57
@ksteimel  that took longer than expected but the fresh branch is now merged

**Comment by Ayushk4** [comment] 2018-12-29 06:40
I would like to work on this issue.

**Comment by oxinabox** [comment] 2018-12-29 15:56
Feel free.
I will review any PRs.

**Comment by Ayushk4** [comment] 2019-01-03 12:04
I am receiving the following error while parsing the senseval2 file. 
`Error parsing "<wf cmd=done id=d00.s09.t01 pos=NNS lemma=other wnsn=0 lexsn=U>others</wf>". ErrorException("type Void has no field captures")`

This error has been traced back to a function similar to the one here -https://github.com/JuliaText/CorpusLoaders.jl/blob/58c824dbff95cbb3c3107377750a54d909944932/src/SemCor.jl#L33

The error is caused by `lexsn` being matched as empty. What might be the best way around this? 
One way could be that - I can do exception handling for this and change the match expression for it.
Is there any better way to do this?

**Comment by oxinabox** [comment] 2019-01-03 14:58
I would not add exception handling.
Julia code prefers to be written to avoid exceptions rather than handle them,.
(Unlike python julia exception handling is pretty slow).


I think the regex can probably be relaxed some
this bit: 
`lexsn=(\d.*:\d*)`

So that `U` is also acceptable.
Some of the logic after that also will wnat adjusting.
But in the `SenseAnnotatedWord`
the type of the `lexen` field is still `String`

**Closed** 2019-01-08 14:00 UTC
Labels: good first issue, new-corpus
